SCRIPT=menuScript.sh

run:
	chmod +x $(SCRIPT)
	./$(SCRIPT)

chmod:
	chmod +x $(SCRIPT)

edit:
	nano $(SCRIPT)

clean:
	rm -f *.txt

help:
	@echo "Available commands:"
	@echo "  make run    - Make the script executable and run it"
	@echo "  make chmod  - Make the script executable"
	@echo "  make edit   - Open the script in nano"
	@echo "  make clean  - Remove .txt files from the current directory"
	@echo "  make help   - Show this help menu"
